export const CASES_CREATE_CASEFILE_ROUTING_TITLES = {
  caseType: 'Create a case',
  taskList: 'Case details',
  respondentDetails: 'Respondent details',
  applicantIndividual: 'Applicant details - Individual',
  applicantOrganisation: 'Applicant details - Organisation',
  centralAuthorityDetails: 'Central authority details',
  orderDetails: 'Order details',
  orderTermsSummary: 'Order terms',
  orderTermsSelect: 'What type of order are you adding?',
  orderTermsInput: 'Order term',
  orderTermCreditor: 'Creditor',
  minorCreditorDetails: 'Minor creditor details',
  minorCreditorSummary: 'Minor creditor summary',
  interestAndIndexation: 'Interest and indexation',
  managingPayments: 'Managing payments',
  commentsAndNotes: 'Comments and notes',
  checkCaseDetails: 'Check case details',
  cancel: 'Cancel case creation',
} as const;
