export const CASES_CREATE_CASEFILE_MINOR_CREDITOR_FIELD_NAMES = {
  creditorType: 'create_casefile_minor_creditor_type',
  title: 'create_casefile_minor_creditor_title',
  firstNames: 'create_casefile_minor_creditor_first_names',
  lastName: 'create_casefile_minor_creditor_last_name',
  organisationName: 'create_casefile_minor_creditor_organisation_name',
  addressLine1: 'create_casefile_minor_creditor_address_line_1',
  addressLine2: 'create_casefile_minor_creditor_address_line_2',
  addressLine3: 'create_casefile_minor_creditor_address_line_3',
  addressLine4: 'create_casefile_minor_creditor_address_line_4',
  addressLine5: 'create_casefile_minor_creditor_address_line_5',
  postalOrZipCode: 'create_casefile_minor_creditor_postal_or_zip_code',
  countryId: 'create_casefile_minor_creditor_country_id',
  bankType: 'create_casefile_minor_creditor_bank_type',
  ukNameOnAccount: 'create_casefile_minor_creditor_uk_bank_name_on_account',
  ukSortCode: 'create_casefile_minor_creditor_uk_bank_sort_code',
  ukAccountNumber: 'create_casefile_minor_creditor_uk_bank_account_number',
  ukPaymentReference: 'create_casefile_minor_creditor_uk_bank_payment_reference',
  nonUkNameOnAccount: 'create_casefile_minor_creditor_non_uk_bank_name_on_account',
  nonUkAccountNumber: 'create_casefile_minor_creditor_non_uk_bank_account_number',
  nonUkPaymentReference: 'create_casefile_minor_creditor_non_uk_bank_payment_reference',
  nonUkBicSwiftCode: 'create_casefile_minor_creditor_non_uk_bank_bic_swift_code',
  nonUkIban: 'create_casefile_minor_creditor_non_uk_bank_iban',
  nonUkBankName: 'create_casefile_minor_creditor_non_uk_bank_name',
  nonUkBranchSortCode: 'create_casefile_minor_creditor_non_uk_bank_branch_sort_code',
} as const;
