import { CASES_CREATE_CASEFILE_MINOR_CREDITOR_FIELD_NAMES as MINOR_FIELDS } from 'src/app/flows/cases/cases-create-casefile/cases-create-casefile-minor-creditor-details/constants/cases-create-casefile-minor-creditor-field-names.constant';
import { CASES_CREATE_CASEFILE_ORDER_DETAILS_FIELD_NAMES as ORDER_FIELDS } from 'src/app/flows/cases/cases-create-casefile/cases-create-casefile-order-details/constants/cases-create-casefile-order-details-field-names.constant';
import { CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES } from 'src/app/flows/cases/cases-create-casefile/cases-create-casefile-case-type/constants/cases-create-casefile-case-type-field-names.constant';
import { CASES_CREATE_CASEFILE_CENTRAL_AUTHORITY_FIELD_NAMES } from 'src/app/flows/cases/cases-create-casefile/cases-create-casefile-central-authority/constants/cases-create-casefile-central-authority-field-names.constant';
import { CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES } from 'src/app/flows/cases/cases-create-casefile/cases-create-casefile-interest-indexation/constants/cases-create-casefile-interest-indexation-field-names.constant';
import { CASES_CREATE_CASEFILE_MANAGING_PAYMENTS_FIELD_NAMES } from 'src/app/flows/cases/cases-create-casefile/cases-create-casefile-managing-payments/constants/cases-create-casefile-managing-payments-field-names.constant';
import { CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES } from 'src/app/flows/cases/cases-create-casefile/cases-create-casefile-comments-notes/constants/cases-create-casefile-comments-notes-field-names.constant';
import { CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES } from 'src/app/flows/cases/cases-create-casefile/cases-create-casefile-order-term-creditor/constants/cases-create-casefile-order-term-creditor-field-names.constant';

export const CreateCasefileSelectors = {
  caseTypeHeading: '#create_casefile_case_type_heading',
  cancellation: {
    heading: '#create_casefile_cancel_heading',
    warning: '#create_casefile_cancel_warning',
    confirm: '#create_casefile_cancel_confirm',
    back: '#create_casefile_cancel_back a',
    error: '#create_casefile_cancel_error',
  },
  review: {
    heading: '#review-heading',
    confirmationNextSteps: '#submission-confirmation-next-steps',
    createNew: '#create_casefile_confirmation_create_new',
    inReview: '#create_casefile_confirmation_in_review',
    retry: '#create_casefile_confirmation_retry',
    confirmationHeading: '#submission-confirmation-heading',
    section: (id: string) => `#review-${id}`,
    change: (id: string) => `#review-${id}-change`,
    bankDetails: '#review-applicant-bank details',
    bankToggle: '#review-applicant-bank summary',
    submit: '#create_casefile_review_submit',
    cancel: '#create_casefile_review_cancel',
    errors: '#review-errors',
    termChange: (termId: number) => `#review-term-change-${termId}`,
    termRemove: (termId: number) => `#review-term-remove-${termId}`,
  },
  heading: 'h1',
  globalErrorBanner: '.moj-alert--error',
  globalErrorBannerHeading: '.moj-alert--error .moj-alert__heading',
  globalErrorBannerContent: '.moj-alert--error .moj-alert__content',
  caseTypeGroup: `#${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.caseType}`,
  caseTypeLegend: `#${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.caseType} legend`,
  caseTypeRadios: `input[name="${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.caseType}"]`,
  caseTypeLabels: `#${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.caseType} .govuk-radios__label`,
  caseTypeRadio: (value: string) =>
    `input[name="${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.caseType}"][value="${value}"]`,
  remoInDescription: `#${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.caseType}-remo-in-description`,
  applicantConditional: '#applicantTypeConditional',
  applicantType: `#${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.applicantType}`,
  applicantTypeLabel: `label[for="${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.applicantType}"]`,
  applicantTypeSelectedOption: `#${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.applicantType} option:selected`,
  continueButton: '#continue',
  cancelLink: '#cancelCaseType a',
  errorSummary: '.govuk-error-summary',
  errorSummaryLinks: '.govuk-error-summary a',
  caseTypeError: `#${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.caseType}-error-message`,
  applicantTypeError: `#${CASES_CREATE_CASEFILE_CASE_TYPE_FIELD_NAMES.applicantType}-error-message`,
  orderDetails: {
    heading: 'h1',
    application: `#${ORDER_FIELDS.applicationId}-autocomplete`,
    applicationOptions: `#${ORDER_FIELDS.applicationId}-autocomplete__listbox [role="option"]`,
    court: `#${ORDER_FIELDS.court}`,
    dateOrderMade: `#${ORDER_FIELDS.dateOrderMade}`,
    orderCalendar: `#${ORDER_FIELDS.dateOrderMade} + .moj-js-datepicker-toggle`,
    paymentFrequency: `#${ORDER_FIELDS.paymentFrequency}`,
    frequencyOptions: `#${ORDER_FIELDS.paymentFrequency} option`,
    dateArrearsLastUpdated: `#${ORDER_FIELDS.dateArrearsLastUpdated}`,
    arrearsCalendar: `#${ORDER_FIELDS.dateArrearsLastUpdated} + .moj-js-datepicker-toggle`,
    calendar: `#datepicker-${ORDER_FIELDS.dateOrderMade}`,
    calendarDay: '.moj-datepicker__calendar button:not([disabled])',
    returnButton: '#create_casefile_order_details_return_to_case_details',
    cancel: '#create_casefile_order_details_cancel a',
    back: '.govuk-back-link',
  },
  orderTerms: {
    heading: 'h1',
    select: '#create_casefile_order_terms_select_result_id',
    selectError: '#create_casefile_order_terms_select_result_id-error-message',
    continueButton: '#create_casefile_order_terms_continue',
    cancel: '#create_casefile_order_terms_cancel a',
    retry: '#create_casefile_order_terms_retry',
    status: '#create_casefile_order_terms_status',
    add: '#create_casefile_order_terms_add',
    return: '#create_casefile_order_terms_return',
    back: 'a.govuk-back-link',
  },
  orderTermsSummary: {
    cards: '[data-order-term-id]',
    card: (termId: number) => `[data-order-term-id="${termId}"]`,
    change: (termId: number) => `#order-term-${termId}-change`,
    remove: (termId: number) => `#order-term-${termId}-remove`,
    creditorToggle: (termId: number) => `#order-term-${termId}-bank summary`,
    creditorDetails: (termId: number) => `#order-term-${termId}-bank .govuk-details__text`,
    creditorDisclosure: (termId: number) => `#order-term-${termId}-bank details`,
    removeReturn: '#create_casefile_order_terms_remove_return',
  },
  orderTermsInput: {
    form: 'app-cases-create-casefile-order-terms-input-form form',
    radioOption: '#create_casefile_order_terms_input_choice-option-0',
    checkboxFieldset: '#create_casefile_order_terms_input_confirm-fieldset',
    autocompleteOptions: '#create_casefile_order_terms_input_lookup-autocomplete__listbox [role="option"]',
    inlineErrors: '.govuk-error-message',
    metadataMarkup:
      'app-cases-create-casefile-order-terms-input-form strong, app-cases-create-casefile-order-terms-input-form img',
    amount: '#create_casefile_order_terms_input_amount',
    frequency: '#create_casefile_order_terms_input_frequency',
    expiry: '#create_casefile_order_terms_input_expiry_date',
    arrears: '#create_casefile_order_terms_input_arrears',
    childName: '#create_casefile_order_terms_input_child_name',
    childBirth: '#create_casefile_order_terms_input_child_date_of_birth',
    continueButton: '#create_casefile_order_terms_input_continue',
    cancel: '#create_casefile_order_terms_input_cancel a',
    amendmentCancel: '#order-term-amendment-cancel .button-link',
    creditorReturn: '#create_casefile_order_term_creditor_return',
    shortText: '#create_casefile_order_terms_input_short_text',
    shortTextLabel: 'label[for="create_casefile_order_terms_input_short_text"]',
    shortTextHint: '#create_casefile_order_terms_input_short_text-hint',
    longText: '#create_casefile_order_terms_input_long_text',
    integer: '#create_casefile_order_terms_input_count',
    radio: '#create_casefile_order_terms_input_choice',
    select: '#create_casefile_order_terms_input_menu',
    autocomplete: '#create_casefile_order_terms_input_lookup-autocomplete',
    checkbox: '#create_casefile_order_terms_input_confirm',
  },
  creditor: {
    applicant: `#${CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES.choice}-applicant`,
    major: `#${CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES.choice}-major`,
    majorId: `#${CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES.majorCreditorId}`,
    addNew: `#${CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES.choice}-add-new`,
    minor: (sequenceNumber: number) =>
      `#${CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES.choice}-minor-${sequenceNumber}`,
    choiceFieldset: `#${CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES.choice}`,
    choiceError: `#${CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES.choice}-error-message`,
    majorError: `#${CASES_CREATE_CASEFILE_ORDER_TERM_CREDITOR_FIELD_NAMES.majorCreditorId}-error-message`,
    continueButton: '#create_casefile_order_term_creditor_continue',
    cancel: '#create_casefile_order_term_creditor_cancel a',
  },
  minorCreditor: {
    individual: `#${MINOR_FIELDS.creditorType}-individual`,
    organisation: `#${MINOR_FIELDS.creditorType}-organisation`,
    type: `#${MINOR_FIELDS.creditorType}`,
    bankUk: `#${MINOR_FIELDS.bankType}-uk`,
    bankNonUk: `#${MINOR_FIELDS.bankType}-non-uk`,
    bankNone: `#${MINOR_FIELDS.bankType}-none`,
    bankType: `#${MINOR_FIELDS.bankType}`,
    title: `#${MINOR_FIELDS.title}`,
    firstNames: `#${MINOR_FIELDS.firstNames}`,
    lastName: `#${MINOR_FIELDS.lastName}`,
    organisationName: `#${MINOR_FIELDS.organisationName}`,
    addressLine1: `#${MINOR_FIELDS.addressLine1}`,
    addressLine2: `#${MINOR_FIELDS.addressLine2}`,
    addressLine3: `#${MINOR_FIELDS.addressLine3}`,
    addressLine4: `#${MINOR_FIELDS.addressLine4}`,
    addressLine5: `#${MINOR_FIELDS.addressLine5}`,
    postalOrZipCode: `#${MINOR_FIELDS.postalOrZipCode}`,
    countryId: `#${MINOR_FIELDS.countryId}`,
    countryAutocomplete: `#${MINOR_FIELDS.countryId}-autocomplete`,
    ukNameOnAccount: `#${MINOR_FIELDS.ukNameOnAccount}`,
    ukSortCode: `#${MINOR_FIELDS.ukSortCode}`,
    ukAccountNumber: `#${MINOR_FIELDS.ukAccountNumber}`,
    ukPaymentReference: `#${MINOR_FIELDS.ukPaymentReference}`,
    nonUkNameOnAccount: `#${MINOR_FIELDS.nonUkNameOnAccount}`,
    nonUkAccountNumber: `#${MINOR_FIELDS.nonUkAccountNumber}`,
    nonUkPaymentReference: `#${MINOR_FIELDS.nonUkPaymentReference}`,
    nonUkBicSwiftCode: `#${MINOR_FIELDS.nonUkBicSwiftCode}`,
    nonUkIban: `#${MINOR_FIELDS.nonUkIban}`,
    nonUkBankName: `#${MINOR_FIELDS.nonUkBankName}`,
    nonUkBranchSortCode: `#${MINOR_FIELDS.nonUkBranchSortCode}`,
    countryOptions: `#${MINOR_FIELDS.countryId}-autocomplete__listbox [role="option"]`,
    save: '#create_casefile_minor_creditor_save',
    cancel: '#create_casefile_minor_creditor_cancel a',
  },
  minorCreditorSummary: {
    change: '#Change',
    remove: '#Remove',
    continue: '#minor-creditor-summary-continue',
    cancel: 'opal-lib-govuk-cancel-link a',
    rows: 'opal-lib-govuk-summary-list .govuk-summary-list__row',
    rowValue: (name: string) => `#minorCreditorDetails${name}Value`,
  },
  minorCreditorRemoval: {
    heading: '#create_casefile_minor_creditor_remove_heading',
    confirm: '#create_casefile_minor_creditor_remove_confirm',
    cancel: '#create_casefile_minor_creditor_remove_cancel',
    retry: '#create_casefile_minor_creditor_remove_retry',
    recover: '#create_casefile_minor_creditor_remove_recover',
    success: '#create_casefile_order_term_creditor_removal_success',
    dismiss: '#create_casefile_order_term_creditor_removal_success button',
    creditorHeading: '#create_casefile_order_term_creditor_heading',
    card: '#minorCreditorRemovalDetails',
    rowValue: (name: string) => `#minorCreditorRemovalDetails${name}Value`,
  },
  minorCreditorDetails: {
    returnLink: '#returnToCreditor',
  },
  liveAnnouncement: '.moj-alert--error [role="alert"]',
  primaryNavigation: '#primaryNavigation',
  caseDetails: {
    backLink: '.govuk-back-link',
    caption: '.govuk-caption-l',
    heading: 'h1',
    caseTypeRow: '#caseDetailsCaseType',
    caseTypeValue: '#caseDetailsCaseTypeValue',
    applicantTypeRow: '#caseDetailsApplicantType',
    applicantTypeValue: '#caseDetailsApplicantTypeValue',
    taskNames: '.govuk-task-list__name-and-hint',
    partyDetails: '#partyDetails',
    order: '#order',
    additionalInformation: '#additionalInformation',
    respondentItem: '#respondentItem',
    respondentLink: '#respondentItem a',
    respondentStatus: '#respondentStatus',
    applicantItem: '#applicantItem',
    applicantLink: '#applicantItem a',
    applicantStatus: '#applicantStatus',
    centralAuthorityItem: '#centralAuthorityItem',
    centralAuthorityLink: '#centralAuthorityItem a',
    centralAuthorityStatus: '#centralAuthorityStatus',
    orderDetailsItem: '#orderDetailsItem',
    orderDetailsLink: '#orderDetailsItem a',
    orderDetailsStatus: '#orderDetailsStatus',
    orderTermsItem: '#orderTermsItem',
    orderTermsLink: '#orderTermsItem a',
    orderTermsStatus: '#orderTermsStatus',
    interestAndIndexationItem: '#interestAndIndexationItem',
    interestAndIndexationLink: '#interestAndIndexationItem a',
    interestAndIndexationStatus: '#interestAndIndexationStatus',
    managingPaymentsItem: '#managingPaymentsItem',
    managingPaymentsLink: '#managingPaymentsItem a',
    managingPaymentsStatus: '#managingPaymentsStatus',
    commentsAndNotesItem: '#commentsAndNotesItem',
    commentsAndNotesLink: '#commentsAndNotesItem a',
    commentsAndNotesStatus: '#commentsAndNotesStatus',
    blockingGuidance: '#checkCaseBlockingGuidance',
    checkCaseButton: '#checkCaseButton',
    cancelLink: '#cancelCaseCreation',
  },
  centralAuthority: {
    heading: 'h1',
    remoReference: `#${CASES_CREATE_CASEFILE_CENTRAL_AUTHORITY_FIELD_NAMES.remoReference}`,
    centralAuthorityReference: `#${CASES_CREATE_CASEFILE_CENTRAL_AUTHORITY_FIELD_NAMES.centralAuthorityReference}`,
    majorCreditorId: `#${CASES_CREATE_CASEFILE_CENTRAL_AUTHORITY_FIELD_NAMES.majorCreditorId}`,
    autocomplete: `#${CASES_CREATE_CASEFILE_CENTRAL_AUTHORITY_FIELD_NAMES.majorCreditorId}-autocomplete`,
    autocompleteOptions: `#${CASES_CREATE_CASEFILE_CENTRAL_AUTHORITY_FIELD_NAMES.majorCreditorId}-autocomplete__listbox [role="option"]`,
    remoReferenceError: `#${CASES_CREATE_CASEFILE_CENTRAL_AUTHORITY_FIELD_NAMES.remoReference}-error-message`,
    centralAuthorityReferenceError: `#${CASES_CREATE_CASEFILE_CENTRAL_AUTHORITY_FIELD_NAMES.centralAuthorityReference}-error-message`,
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelCentralAuthority a',
  },
  interestAndIndexation: {
    heading: 'h1',
    interestGroup: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.interestApplies}`,
    interestLegend: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.interestApplies} legend`,
    interestRadios: `input[name="${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.interestApplies}"]`,
    interestLabels: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.interestApplies} .govuk-radios__label`,
    interestRadio: (value: boolean) =>
      `input[name="${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.interestApplies}"][value="${String(value)}"]`,
    indexationGroup: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.indexationType}`,
    indexationLegend: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.indexationType} legend`,
    indexationRadios: `input[name="${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.indexationType}"]`,
    indexationLabels: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.indexationType} .govuk-radios__label`,
    indexationRadio: (value: string) =>
      `input[name="${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.indexationType}"][value="${value}"]`,
    indexationDivider: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.indexationType} .govuk-radios__divider`,
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelInterestAndIndexation a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    interestError: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.interestApplies}-error-message`,
    indexationError: `#${CASES_CREATE_CASEFILE_INTEREST_INDEXATION_FIELD_NAMES.indexationType}-error-message`,
  },
  managingPayments: {
    heading: 'h1',
    paymentArrangementGroup: `#${CASES_CREATE_CASEFILE_MANAGING_PAYMENTS_FIELD_NAMES.paymentArrangement}`,
    paymentArrangementLegend: `#${CASES_CREATE_CASEFILE_MANAGING_PAYMENTS_FIELD_NAMES.paymentArrangement} legend`,
    paymentArrangementRadios: `input[name="${CASES_CREATE_CASEFILE_MANAGING_PAYMENTS_FIELD_NAMES.paymentArrangement}"]`,
    paymentArrangementLabels: `#${CASES_CREATE_CASEFILE_MANAGING_PAYMENTS_FIELD_NAMES.paymentArrangement} .govuk-radios__label`,
    paymentArrangementRadio: (value: string) =>
      `input[name="${CASES_CREATE_CASEFILE_MANAGING_PAYMENTS_FIELD_NAMES.paymentArrangement}"][value="${value}"]`,
    directHint: `#${CASES_CREATE_CASEFILE_MANAGING_PAYMENTS_FIELD_NAMES.paymentArrangement}-direct-item-hint`,
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelManagingPayments a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    paymentArrangementError: `#${CASES_CREATE_CASEFILE_MANAGING_PAYMENTS_FIELD_NAMES.paymentArrangement}-error-message`,
  },
  commentsAndNotes: {
    heading: 'h1',
    inset: '#commentsAndNotesInset',
    comment: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.comment}`,
    commentLabel: `label[for="${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.comment}"]`,
    commentHint: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.comment}-hint`,
    commentLimit: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.comment}-with-hint-info`,
    commentCounter: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.comment} ~ .govuk-character-count__status`,
    commentError: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.comment}-error-message`,
    note: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.note}`,
    noteLabel: `label[for="${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.note}"]`,
    noteHint: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.note}-hint`,
    noteLimit: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.note}-with-hint-info`,
    noteCounter: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.note} ~ .govuk-character-count__status`,
    noteError: `#${CASES_CREATE_CASEFILE_COMMENTS_NOTES_FIELD_NAMES.note}-error-message`,
    sectionBreak: '.govuk-section-break--visible',
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelCommentsAndNotes a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
  },
  respondentDetails: {
    heading: 'h1',
    sectionHeadings: 'h2',
    title: '#create_casefile_respondent_details_title',
    firstNames: '#create_casefile_respondent_details_first_names',
    lastName: '#create_casefile_respondent_details_last_name',
    addAliases: '#create_casefile_respondent_details_add_aliases',
    aliasesConditional: '#respondentAliasesConditional-conditional',
    aliasFirstNames: 'input[id^="create_casefile_respondent_details_alias_first_names_"]',
    aliasLastNames: 'input[id^="create_casefile_respondent_details_alias_last_name_"]',
    aliasFirstName: (index: number) => `#create_casefile_respondent_details_alias_first_names_${index}`,
    aliasLastName: (index: number) => `#create_casefile_respondent_details_alias_last_name_${index}`,
    addAliasButton: '#addRespondentAlias',
    removeAliasLink: '#respondentAliasesConditional-conditional a.govuk-link',
    dateOfBirth: '#create_casefile_respondent_details_date_of_birth',
    nationalInsuranceNumber: '#create_casefile_respondent_details_national_insurance_number',
    otherPersonalInformation: '#create_casefile_respondent_details_other_personal_information',
    mainEmailAddress: '#create_casefile_respondent_details_main_email_address',
    otherEmailAddress: '#create_casefile_respondent_details_other_email_address',
    mainTelephoneNumber: '#create_casefile_respondent_details_main_telephone_number',
    otherTelephoneNumber: '#create_casefile_respondent_details_other_telephone_number',
    addressLine1: '#create_casefile_respondent_details_address_line_1',
    addressLine2: '#create_casefile_respondent_details_address_line_2',
    addressLine3: '#create_casefile_respondent_details_address_line_3',
    addressLine4: '#create_casefile_respondent_details_address_line_4',
    addressLine5: '#create_casefile_respondent_details_address_line_5',
    postalOrZipCode: '#create_casefile_respondent_details_postal_or_zip_code',
    countryId: '#create_casefile_respondent_details_country_id',
    countryAutocomplete: '#create_casefile_respondent_details_country_id-autocomplete',
    countryOptions: '#create_casefile_respondent_details_country_id-autocomplete__listbox [role="option"]',
    sendCorrespondenceToThirdParty: '#create_casefile_respondent_details_send_correspondence_to_third_party',
    thirdPartyConditional: '#respondentThirdPartyConditional-conditional',
    thirdPartyNameOrOrganisation: '#create_casefile_respondent_details_third_party_name_or_organisation',
    thirdPartyRelationship: '#create_casefile_respondent_details_third_party_relationship',
    thirdPartyReference: '#create_casefile_respondent_details_third_party_reference',
    thirdPartyAddressLine1: '#create_casefile_respondent_details_third_party_address_line_1',
    thirdPartyAddressLine2: '#create_casefile_respondent_details_third_party_address_line_2',
    thirdPartyAddressLine3: '#create_casefile_respondent_details_third_party_address_line_3',
    thirdPartyAddressLine4: '#create_casefile_respondent_details_third_party_address_line_4',
    thirdPartyAddressLine5: '#create_casefile_respondent_details_third_party_address_line_5',
    thirdPartyPostalOrZipCode: '#create_casefile_respondent_details_third_party_postal_or_zip_code',
    thirdPartyCountry: '#create_casefile_respondent_details_third_party_country_id',
    addEmployerDetails: '#create_casefile_respondent_details_add_employer_details',
    employerConditional: '#respondentEmployerConditional-conditional',
    employerName: '#create_casefile_respondent_details_employer_name',
    employeeReference: '#create_casefile_respondent_details_employee_reference',
    employerEmailAddress: '#create_casefile_respondent_details_employer_email_address',
    employerTelephoneNumber: '#create_casefile_respondent_details_employer_telephone_number',
    employerAddressLine1: '#create_casefile_respondent_details_employer_address_line_1',
    employerAddressLine2: '#create_casefile_respondent_details_employer_address_line_2',
    employerAddressLine3: '#create_casefile_respondent_details_employer_address_line_3',
    employerAddressLine4: '#create_casefile_respondent_details_employer_address_line_4',
    employerAddressLine5: '#create_casefile_respondent_details_employer_address_line_5',
    employerPostalOrZipCode: '#create_casefile_respondent_details_employer_postal_or_zip_code',
    employerCountryId: '#create_casefile_respondent_details_employer_country_id',
    employerCountryAutocomplete: '#create_casefile_respondent_details_employer_country_id-autocomplete',
    employerCountryOptions:
      '#create_casefile_respondent_details_employer_country_id-autocomplete__listbox [role="option"]',
    restrictedInformation: '#create_casefile_respondent_details_restricted_information',
    restrictedInformationConditional: '#respondentRestrictedInformationConditional-conditional',
    restrictedInformationReason: '#create_casefile_respondent_details_restricted_information_reason',
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelRespondentDetails a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    firstNamesError: '#create_casefile_respondent_details_first_names-error-message',
    lastNameError: '#create_casefile_respondent_details_last_name-error-message',
    aliasFirstNameError: (index: number) =>
      `#create_casefile_respondent_details_alias_first_names_${index}-error-message`,
    aliasLastNameError: (index: number) => `#create_casefile_respondent_details_alias_last_name_${index}-error-message`,
    addressLine1Error: '#create_casefile_respondent_details_address_line_1-error-message',
    countryError: '#create_casefile_respondent_details_country_id-autocomplete-error-message',
    thirdPartyNameOrOrganisationError:
      '#create_casefile_respondent_details_third_party_name_or_organisation-error-message',
    thirdPartyRelationshipError: '#create_casefile_respondent_details_third_party_relationship-error-message',
    thirdPartyAddressLine1Error: '#create_casefile_respondent_details_third_party_address_line_1-error-message',
    thirdPartyCountryError: '#create_casefile_respondent_details_third_party_country_id-error-message',
    employerNameError: '#create_casefile_respondent_details_employer_name-error-message',
    employerAddressLine1Error: '#create_casefile_respondent_details_employer_address_line_1-error-message',
    employerCountryError: '#create_casefile_respondent_details_employer_country_id-autocomplete-error-message',
    restrictedInformationReasonError: '#create_casefile_respondent_details_restricted_information_reason-error-message',
  },
  applicantIndividual: {
    heading: 'h1',
    sectionHeadings: 'h2',
    title: '#create_casefile_applicant_individual_title',
    firstNames: '#create_casefile_applicant_individual_first_names',
    lastName: '#create_casefile_applicant_individual_last_name',
    addAliases: '#create_casefile_applicant_individual_add_aliases',
    aliasesConditional: '#applicantAliasesConditional-conditional',
    aliasFirstNames: 'input[id^="create_casefile_applicant_individual_alias_first_names_"]',
    aliasLastNames: 'input[id^="create_casefile_applicant_individual_alias_last_name_"]',
    aliasFirstName: (index: number) => `#create_casefile_applicant_individual_alias_first_names_${index}`,
    aliasLastName: (index: number) => `#create_casefile_applicant_individual_alias_last_name_${index}`,
    addAliasButton: '#addApplicantAlias',
    removeAliasLink: '#applicantAliasesConditional-conditional a.govuk-link',
    dateOfBirth: '#create_casefile_applicant_individual_date_of_birth',
    dateOfBirthCalendarButton: '#create_casefile_applicant_individual_date_of_birth + .moj-js-datepicker-toggle',
    mainEmailAddress: '#create_casefile_applicant_individual_main_email_address',
    otherEmailAddress: '#create_casefile_applicant_individual_other_email_address',
    mainTelephoneNumber: '#create_casefile_applicant_individual_main_telephone_number',
    otherTelephoneNumber: '#create_casefile_applicant_individual_other_telephone_number',
    addressLine1: '#create_casefile_applicant_individual_address_line_1',
    addressLine2: '#create_casefile_applicant_individual_address_line_2',
    addressLine3: '#create_casefile_applicant_individual_address_line_3',
    addressLine4: '#create_casefile_applicant_individual_address_line_4',
    addressLine5: '#create_casefile_applicant_individual_address_line_5',
    postalOrZipCode: '#create_casefile_applicant_individual_postal_or_zip_code',
    countryId: '#create_casefile_applicant_individual_country_id',
    countryAutocomplete: '#create_casefile_applicant_individual_country_id-autocomplete',
    countryOptions: '#create_casefile_applicant_individual_country_id-autocomplete__listbox [role="option"]',
    sendCorrespondenceToThirdParty: '#create_casefile_applicant_individual_send_correspondence_to_third_party',
    thirdPartyConditional: '#applicantThirdPartyConditional-conditional',
    thirdPartyNameOrOrganisation: '#create_casefile_applicant_individual_third_party_name_or_organisation',
    thirdPartyRelationship: '#create_casefile_applicant_individual_third_party_relationship',
    thirdPartyReference: '#create_casefile_applicant_individual_third_party_reference',
    thirdPartyAddressLine1: '#create_casefile_applicant_individual_third_party_address_line_1',
    thirdPartyAddressLine2: '#create_casefile_applicant_individual_third_party_address_line_2',
    thirdPartyAddressLine3: '#create_casefile_applicant_individual_third_party_address_line_3',
    thirdPartyAddressLine4: '#create_casefile_applicant_individual_third_party_address_line_4',
    thirdPartyAddressLine5: '#create_casefile_applicant_individual_third_party_address_line_5',
    thirdPartyPostalOrZipCode: '#create_casefile_applicant_individual_third_party_postal_or_zip_code',
    thirdPartyCountry: '#create_casefile_applicant_individual_third_party_country_id',
    bankTypeGroup: '#create_casefile_applicant_individual_bank_type',
    bankTypeRadios: 'input[name="create_casefile_applicant_individual_bank_type"]',
    bankTypeRadio: (value: string) => `#create_casefile_applicant_individual_bank_type-${value}`,
    ukBankConditional: '#applicantUkBankConditional',
    ukBankNameOnAccount: '#create_casefile_applicant_individual_uk_bank_name_on_account',
    ukBankSortCode: '#create_casefile_applicant_individual_uk_bank_sort_code',
    ukBankAccountNumber: '#create_casefile_applicant_individual_uk_bank_account_number',
    ukBankPaymentReference: '#create_casefile_applicant_individual_uk_bank_payment_reference',
    nonUkBankConditional: '#applicantNonUkBankConditional',
    nonUkBankNameOnAccount: '#create_casefile_applicant_individual_non_uk_bank_name_on_account',
    nonUkBankAccountNumber: '#create_casefile_applicant_individual_non_uk_bank_account_number',
    nonUkBankPaymentReference: '#create_casefile_applicant_individual_non_uk_bank_payment_reference',
    nonUkBankBicSwiftCode: '#create_casefile_applicant_individual_non_uk_bank_bic_swift_code',
    nonUkBankIban: '#create_casefile_applicant_individual_non_uk_bank_iban',
    nonUkBankName: '#create_casefile_applicant_individual_non_uk_bank_name',
    nonUkBankBranchSortCode: '#create_casefile_applicant_individual_non_uk_bank_branch_sort_code',
    restrictedInformation: '#create_casefile_applicant_individual_restricted_information',
    restrictedInformationConditional: '#applicantRestrictedInformationConditional-conditional',
    restrictedInformationReason: '#create_casefile_applicant_individual_restricted_information_reason',
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelApplicantDetails a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    titleError: '#create_casefile_applicant_individual_title-error-message',
    firstNamesError: '#create_casefile_applicant_individual_first_names-error-message',
    lastNameError: '#create_casefile_applicant_individual_last_name-error-message',
    aliasFirstNameError: (index: number) =>
      `#create_casefile_applicant_individual_alias_first_names_${index}-error-message`,
    aliasLastNameError: (index: number) =>
      `#create_casefile_applicant_individual_alias_last_name_${index}-error-message`,
    dateOfBirthError: '#create_casefile_applicant_individual_date_of_birth-error-message',
    mainEmailAddressError: '#create_casefile_applicant_individual_main_email_address-error-message',
    otherEmailAddressError: '#create_casefile_applicant_individual_other_email_address-error-message',
    mainTelephoneNumberError: '#create_casefile_applicant_individual_main_telephone_number-error-message',
    otherTelephoneNumberError: '#create_casefile_applicant_individual_other_telephone_number-error-message',
    addressLine1Error: '#create_casefile_applicant_individual_address_line_1-error-message',
    addressLine2Error: '#create_casefile_applicant_individual_address_line_2-error-message',
    addressLine3Error: '#create_casefile_applicant_individual_address_line_3-error-message',
    addressLine4Error: '#create_casefile_applicant_individual_address_line_4-error-message',
    addressLine5Error: '#create_casefile_applicant_individual_address_line_5-error-message',
    postalOrZipCodeError: '#create_casefile_applicant_individual_postal_or_zip_code-error-message',
    countryError: '#create_casefile_applicant_individual_country_id-autocomplete-error-message',
    thirdPartyNameOrOrganisationError:
      '#create_casefile_applicant_individual_third_party_name_or_organisation-error-message',
    thirdPartyRelationshipError: '#create_casefile_applicant_individual_third_party_relationship-error-message',
    thirdPartyReferenceError: '#create_casefile_applicant_individual_third_party_reference-error-message',
    thirdPartyAddressLine1Error: '#create_casefile_applicant_individual_third_party_address_line_1-error-message',
    thirdPartyAddressLine2Error: '#create_casefile_applicant_individual_third_party_address_line_2-error-message',
    thirdPartyAddressLine3Error: '#create_casefile_applicant_individual_third_party_address_line_3-error-message',
    thirdPartyAddressLine4Error: '#create_casefile_applicant_individual_third_party_address_line_4-error-message',
    thirdPartyAddressLine5Error: '#create_casefile_applicant_individual_third_party_address_line_5-error-message',
    thirdPartyPostalOrZipCodeError:
      '#create_casefile_applicant_individual_third_party_postal_or_zip_code-error-message',
    thirdPartyCountryError: '#create_casefile_applicant_individual_third_party_country_id-error-message',
    bankTypeError: '#create_casefile_applicant_individual_bank_type-error-message',
    ukBankNameOnAccountError: '#create_casefile_applicant_individual_uk_bank_name_on_account-error-message',
    ukBankSortCodeError: '#create_casefile_applicant_individual_uk_bank_sort_code-error-message',
    ukBankAccountNumberError: '#create_casefile_applicant_individual_uk_bank_account_number-error-message',
    ukBankPaymentReferenceError: '#create_casefile_applicant_individual_uk_bank_payment_reference-error-message',
    nonUkBankNameOnAccountError: '#create_casefile_applicant_individual_non_uk_bank_name_on_account-error-message',
    nonUkBankAccountNumberError: '#create_casefile_applicant_individual_non_uk_bank_account_number-error-message',
    nonUkBankBicSwiftCodeError: '#create_casefile_applicant_individual_non_uk_bank_bic_swift_code-error-message',
    nonUkBankIbanError: '#create_casefile_applicant_individual_non_uk_bank_iban-error-message',
    nonUkBankBranchSortCodeError: '#create_casefile_applicant_individual_non_uk_bank_branch_sort_code-error-message',
    restrictedInformationReasonError:
      '#create_casefile_applicant_individual_restricted_information_reason-error-message',
  },
  applicantOrganisation: {
    heading: 'h1',
    sectionHeadings: 'h2',
    organisationName: '#create_casefile_applicant_organisation_name',
    foreignAuthorityReference: '#create_casefile_applicant_organisation_foreign_authority_reference',
    mainEmailAddress: '#create_casefile_applicant_organisation_main_email_address',
    otherEmailAddress: '#create_casefile_applicant_organisation_other_email_address',
    mainTelephoneNumber: '#create_casefile_applicant_organisation_main_telephone_number',
    otherTelephoneNumber: '#create_casefile_applicant_organisation_other_telephone_number',
    addressLine1: '#create_casefile_applicant_organisation_address_line_1',
    addressLine2: '#create_casefile_applicant_organisation_address_line_2',
    addressLine3: '#create_casefile_applicant_organisation_address_line_3',
    addressLine4: '#create_casefile_applicant_organisation_address_line_4',
    addressLine5: '#create_casefile_applicant_organisation_address_line_5',
    postalOrZipCode: '#create_casefile_applicant_organisation_postal_or_zip_code',
    countryId: '#create_casefile_applicant_organisation_country_id',
    countryAutocomplete: '#create_casefile_applicant_organisation_country_id-autocomplete',
    countryOptions: '#create_casefile_applicant_organisation_country_id-autocomplete__listbox [role="option"]',
    bankTypeGroup: '#create_casefile_applicant_organisation_bank_type',
    bankTypeRadios: 'input[name="create_casefile_applicant_organisation_bank_type"]',
    bankTypeRadio: (value: string) => `#create_casefile_applicant_organisation_bank_type-${value}`,
    ukBankConditional: '#applicantUkBankConditional',
    ukBankNameOnAccount: '#create_casefile_applicant_organisation_uk_bank_name_on_account',
    ukBankSortCode: '#create_casefile_applicant_organisation_uk_bank_sort_code',
    ukBankAccountNumber: '#create_casefile_applicant_organisation_uk_bank_account_number',
    ukBankPaymentReference: '#create_casefile_applicant_organisation_uk_bank_payment_reference',
    nonUkBankConditional: '#applicantNonUkBankConditional',
    nonUkBankNameOnAccount: '#create_casefile_applicant_organisation_non_uk_bank_name_on_account',
    nonUkBankBicSwiftCode: '#create_casefile_applicant_organisation_non_uk_bank_bic_swift_code',
    nonUkBankIban: '#create_casefile_applicant_organisation_non_uk_bank_iban',
    nonUkBankPaymentReference: '#create_casefile_applicant_organisation_non_uk_bank_payment_reference',
    nonUkBankName: '#create_casefile_applicant_organisation_non_uk_bank_name',
    nonUkBankBranchSortCode: '#create_casefile_applicant_organisation_non_uk_bank_branch_sort_code',
    nonUkBankAccountNumber: '#create_casefile_applicant_organisation_non_uk_bank_account_number',
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelApplicantDetails a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    organisationNameError: '#create_casefile_applicant_organisation_name-error-message',
    foreignAuthorityReferenceError: '#create_casefile_applicant_organisation_foreign_authority_reference-error-message',
    mainEmailAddressError: '#create_casefile_applicant_organisation_main_email_address-error-message',
    otherEmailAddressError: '#create_casefile_applicant_organisation_other_email_address-error-message',
    mainTelephoneNumberError: '#create_casefile_applicant_organisation_main_telephone_number-error-message',
    otherTelephoneNumberError: '#create_casefile_applicant_organisation_other_telephone_number-error-message',
    addressLine1Error: '#create_casefile_applicant_organisation_address_line_1-error-message',
    addressLine2Error: '#create_casefile_applicant_organisation_address_line_2-error-message',
    addressLine3Error: '#create_casefile_applicant_organisation_address_line_3-error-message',
    addressLine4Error: '#create_casefile_applicant_organisation_address_line_4-error-message',
    addressLine5Error: '#create_casefile_applicant_organisation_address_line_5-error-message',
    postalOrZipCodeError: '#create_casefile_applicant_organisation_postal_or_zip_code-error-message',
    countryError: '#create_casefile_applicant_organisation_country_id-autocomplete-error-message',
    bankTypeError: '#create_casefile_applicant_organisation_bank_type-error-message',
    ukBankNameOnAccountError: '#create_casefile_applicant_organisation_uk_bank_name_on_account-error-message',
    ukBankSortCodeError: '#create_casefile_applicant_organisation_uk_bank_sort_code-error-message',
    ukBankAccountNumberError: '#create_casefile_applicant_organisation_uk_bank_account_number-error-message',
    ukBankPaymentReferenceError: '#create_casefile_applicant_organisation_uk_bank_payment_reference-error-message',
    nonUkBankNameOnAccountError: '#create_casefile_applicant_organisation_non_uk_bank_name_on_account-error-message',
    nonUkBankBicSwiftCodeError: '#create_casefile_applicant_organisation_non_uk_bank_bic_swift_code-error-message',
    nonUkBankIbanError: '#create_casefile_applicant_organisation_non_uk_bank_iban-error-message',
    nonUkBankBranchSortCodeError: '#create_casefile_applicant_organisation_non_uk_bank_branch_sort_code-error-message',
    nonUkBankAccountNumberError: '#create_casefile_applicant_organisation_non_uk_bank_account_number-error-message',
  },
} as const;
